version: "3"

services:
  linkedin-bot:
    image: busshi/linkedin_bot:latest

    pull_policy: always

    container_name: linkedin_bot

    volumes:
      - .env:/opt/app/bot/.env
      - ./data:/opt/app/bot/data

    restart: on-failure:5
